### ISSUE TITLE
Can't get a title while playing adventure mode

### ISSUE THREAD

**Issue by kirderf1** [Putnam3145/fortbent#5]
I do not know the conditions for when it works or not, but this is very likely relevant:
`...hack/lua/split.lua:7: attempt to index local 'str' (a nil value)
stack traceback:
...hack/lua/split.lua:7: in function 'split'
...data/save/region2/raw/scripts/base/classes.lua:85: in function <...data/save/region2/raw/scripts/base/classes.lua:50>`

**Comment by kirderf1** [comment]
Looking at it now, the stacktrace is actually pointing to it failing giving the character experience because it's missing a title, and not for failing to apply a title.

**Comment by Putnam3145** [comment]
Ugh. I'm using someone else's code for that, and I am almost entirely unsure as to what exactly this problem is.

**Comment by Putnam3145** [comment]
It may be possible that you are getting the title and it's simply not noticeable because you don't have any experience yet, but then again the title should be showing up on the (l)ook menu AFAIK.

**Comment by kirderf1** [comment]
No title showed up when (l)ooking. And I know where to look because I have checked that way during the times that I had a title.
Here's another thing found in the command window while playing fortress mode:
`...hack/lua/classes/requirements-class.lua:33: attempt to compare nil with number`

**Comment by Putnam3145** [comment]
[Related](http://www.bay12forums.com/smf/index.php?topic=135597.msg6143685#msg6143685)

Now I'm *really* confused.

**Comment by kirderf1** [comment]
I just found out that the version I downloaded was for sometime before 2aa2fb04f850d49f51e5a0cb96ac419dfdf6c37f.

**Comment by kirderf1** [comment]
I'll try to forcefully update and see if I'm still receiving the issue.

**Comment by kirderf1** [comment]
Another thing found while doing that:
`...hack/lua/repeat-util.lua:28: attempt to call upvalue 'func' (a nil value)
...(three more lines here)
...raw/scripts/fortbent/claspect_assign.lua:136: in function 'f'`
You should probably assign or change the `gristTorrent` value there.
BTW, do you know about some way to copy text from that command window?

**Comment by Putnam3145** [comment]
Depends on what OS. On Windows, you can right click on the top bar, go into the edit submenu and click "mark", then use the mouse to highlight and enter to copy to the clipboard.

**Comment by kirderf1** [comment]
Going to try to resolve this to start with:
`...hack\lua\classes\read-file.lua:34: attempt to index
 global 'classes' (a nil value)`
`stack traceback:`
`        ...hack\lua\classes\read-file.lua:34: in funct
ion 'read_file'`
`        ...data/save/region3/raw/scripts/base/classes.lua:25: in funct
ion 'f'`

**Comment by kirderf1** [comment]
Actually, since I am not very experienced with modding dwarf fortress, this would probably be too much effort on my part. Especially since I haven't created a decent coding enviroment for this yet. I should probably go back to minestuck for now.

**Comment by Putnam3145** [comment]
There should be an update for the classes system that seems to be the problem here coming... it's not my code, so fixing it myself could break compatibility with future updates. Ugly situation all around.
